#**Collaborative Filtering**

In [1]:
# Import PySpark components and auxiliary libraries for data manipulation and analysis
from google.colab import drive

import os
import numpy as np

from pyspark.sql import SparkSession
from pyspark.sql.functions import avg, count

from pyspark.sql import functions as F

from pyspark.sql.functions import collect_list, sort_array, udf
from pyspark.sql.types import ArrayType, LongType

from pyspark.sql.functions import explode, col, array, lit

In [2]:
# Mount Drive
drive.mount('/content/drive')

Drive already mounted at /content/drive; to attempt to forcibly remount, call drive.mount("/content/drive", force_remount=True).

In [3]:
# Find Project Folder
def find_project_folder(folder_name="CineFusion", base_path="/content/drive/MyDrive"):
    for root, dirs, files in os.walk(base_path):
        if folder_name in dirs:
            return os.path.join(root, folder_name)
    return None

BASE_DIR = find_project_folder()

if BASE_DIR is None:
    raise Exception("Project folder not found. Make sure it's added to MyDrive.")

print("Project folder found at:", BASE_DIR)

Project folder found at: /content/drive/MyDrive/CineFusion

In [4]:
# Start Spark Session
spark = SparkSession.builder \
    .appName("CineFusion - CF") \
    .config("spark.driver.memory", "12g") \
    .config("spark.executor.memory", "12g") \
    .getOrCreate()

In [5]:
# Import Rating Data from the 25M Dataset
ratings = spark.read.csv(
    f"{BASE_DIR}/ml-25m/ratings.csv",
    header=True,
    inferSchema=True
).select("userId", "movieId", "rating")

movies = spark.read.csv(
    f"{BASE_DIR}/ml-25m/movies.csv",
    header=True,
    inferSchema=True
).select("movieId", "title")

print("Ratings count:", ratings.count())
print("Movies count:", movies.count())

Ratings count: 25000095
Movies count: 62423

In [6]:
# Counting unique entries
ratings_stats = ratings.agg(
    F.min("userId").alias("min_userId"),
    F.max("userId").alias("max_userId"),
    F.min("movieId").alias("min_movieId"),
    F.max("movieId").alias("max_movieId"),
    F.countDistinct("userId").alias("unique_userId"),
    F.countDistinct("movieId").alias("unique_movieId")
).collect()[0]

movies_stats = movies.agg(
    F.min("movieId").alias("min_movieId"),
    F.max("movieId").alias("max_movieId"),
    F.countDistinct("movieId").alias("unique_movieId")
).collect()[0]

print("rating.csv")
print(f"userId : {ratings_stats['min_userId']} -> {ratings_stats['max_userId']}")
print(f"movieId : {ratings_stats['min_movieId']} -> {ratings_stats['max_movieId']}")
print(f"unique userId : {ratings_stats['unique_userId']}")
print(f"unique movieId : {ratings_stats['unique_movieId']}")

print("\nmovies.csv")
print(f"movieId : {movies_stats['min_movieId']} -> {movies_stats['max_movieId']}")
print(f"unique movieId : {movies_stats['unique_movieId']}")

rating.csv
userId : 1 -> 162541
movieId : 1 -> 209171
unique userId : 162541
unique movieId : 59047

movies.csv
movieId : 1 -> 209171
unique movieId : 62423

In [7]:
# Group all movies rated by a user and sort them
user_movies = ratings.groupBy("userId") \
    .agg(sort_array(collect_list("movieId")).alias("movies"))

user_movies.show(5)

+------+--------------------+
|userId|              movies|
+------+--------------------+
|     1|[296, 306, 307, 6...|
|     3|[1, 29, 32, 50, 1...|
|     5|[1, 19, 32, 36, 3...|
|     6|[161, 260, 318, 5...|
|     9|[2, 10, 34, 39, 6...|
+------+--------------------+
only showing top 5 rows

In [ ]:
# Count total number of unique movies rated by all users
all_movies = user_movies.select(explode("movies").alias("movieId")).distinct()
all_movies_list = [row.movieId for row in all_movies.collect()]

print("Number of unique movies:", len(all_movies_list))

Number of unique movies: 59047

In [ ]:
# Generate 100 Permutations of all uniques movies arranged in a random order
k = 100
np.random.seed(42)
permutations = [np.random.permutation(all_movies_list).tolist()
                for _ in range(k)]
permutations_broadcast = spark.sparkContext.broadcast(permutations)

In [ ]:
def minhash_signature(movies):
    perms = permutations_broadcast.value
    sig = []
    movie_set = set(movies)
    for perm in perms:
        for idx, movie in enumerate(perm):
            if movie in movie_set:
                sig.append(idx)
                break
    return sig

minhash_udf = udf(minhash_signature, ArrayType(LongType()))

user_minhash = user_movies.withColumn(
    "minhash", minhash_udf("movies")
).select("userId", "minhash")

user_minhash.show(10)

+------+--------------------+
|userId|             minhash|
+------+--------------------+
|     1|[1666, 1185, 74, ...|
|     3|[30, 5, 74, 13, 1...|
|     5|[363, 44, 74, 430...|
|     6|[4150, 2137, 2034...|
|     9|[449, 616, 421, 2...|
|    12|[3, 241, 74, 13, ...|
|    13|[79, 71, 74, 13, ...|
|    15|[3, 14, 74, 1646,...|
|    16|[7658, 241, 4367,...|
|    17|[79, 334, 1114, 5...|
+------+--------------------+
only showing top 10 rows

In [ ]:
user_minhash.coalesce(1).write \
    .mode("append") \
    .parquet(f"{BASE_DIR}/ml-25m-output/minhash_parquet")

print(f"Saved {user_minhash.count()} user signatures to {BASE_DIR}/ml-25m-output/minhash_parquet")

Saved 162541 user signatures to /content/drive/MyDrive/CineFusion/ml-25m-output/minhash_parquet

In [ ]:
from pyspark.sql.functions import concat_ws

user_minhash_csv = user_minhash.withColumn(
    "minhash",
    concat_ws(",", "minhash")
)

user_minhash_csv.write \
    .mode("append") \
    .option("header", True) \
    .csv(f"{BASE_DIR}/ml-25m-output/minhash_csv")

print(f"Saved {user_minhash.count()} user signatures to {BASE_DIR}/ml-25m-output/minhash_csv")

Saved 162541 user signatures to /content/drive/MyDrive/CineFusion/ml-25m-output/minhash_csv

In [ ]:
from pyspark.sql.functions import col, slice, posexplode, concat_ws, collect_list

b = 20
r = 5
assert b * r == 100

In [ ]:
from pyspark.sql.functions import array

df = user_minhash

for i in range(b):
    df = df.withColumn(
        f"band_{i}",
        slice(col("minhash"), i * r + 1, r)
    )

# df.show()

In [ ]:
band_cols = [f"band_{i}" for i in range(b)]

df_bands = df.select(
    "userId",
    posexplode(array(*[col(c) for c in band_cols])).alias("band_id", "band_values")
)

# df_bands.show()

In [ ]:
from pyspark.sql.functions import hash

df_hashed = df_bands.withColumn(
    "bucket",
    hash(col("band_values"))
)

df_hashed.show()

+------+-------+--------------------+-----------+
|userId|band_id|         band_values|     bucket|
+------+-------+--------------------+-----------+
|     1|      0|[1666, 1185, 74, ...| -783911969|
|     1|      1|[223, 501, 459, 6...| 1292522331|
|     1|      2|[342, 89, 419, 20...|  145431253|
|     1|      3|[1034, 189, 560, ...|  981004731|
|     1|      4|[463, 906, 718, 1...| -914181784|
|     1|      5|[249, 206, 780, 2...|  161219859|
|     1|      6|[1804, 0, 174, 24...|-1551684307|
|     1|      7|[2793, 2945, 1725...| 1296143564|
|     1|      8|[84, 307, 1675, 6...| -786267448|
|     1|      9|[1093, 1166, 1796...|-2095862016|
|     1|     10|[331, 1654, 1340,...| 1608037185|
|     1|     11|[206, 338, 259, 1...| -157102998|
|     1|     12|[417, 1750, 455, ...| 1591976460|
|     1|     13|[969, 116, 137, 7...|-1587558520|
|     1|     14|[2447, 1219, 2834...|-1102942056|
|     1|     15|[263, 554, 1329, ...| -273309605|
|     1|     16|[34, 1516, 8, 215...|-1530362458|
|     1|     17|[594, 334, 630, 1...| 1497685834|
|     1|     18|[753, 902, 454, 4...|  409485980|
|     1|     19|[968, 395, 306, 5...|-1053696134|
+------+-------+--------------------+-----------+
only showing top 20 rows

In [ ]:
df_buckets = df_hashed.groupBy("band_id", "bucket") \
    .agg(collect_list("userId").alias("users")) \
    .filter("size(users) > 1")

df_buckets.show()

ERROR:root:KeyboardInterrupt while sending command.
Traceback (most recent call last):
  File "/usr/local/lib/python3.12/dist-packages/py4j/java_gateway.py", line 1038, in send_command
    response = connection.send_command(command)
               ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/usr/local/lib/python3.12/dist-packages/py4j/clientserver.py", line 535, in send_command
    answer = smart_decode(self.stream.readline()[:-1])
                          ^^^^^^^^^^^^^^^^^^^^^^
  File "/usr/lib/python3.12/socket.py", line 720, in readinto
    return self._sock.recv_into(b)
           ^^^^^^^^^^^^^^^^^^^^^^^
KeyboardInterrupt

KeyboardInterrupt:

In [ ]:
from pyspark.sql.functions import explode

df_pairs = df_buckets.select(
    "band_id",
    explode("users").alias("user1"),
    "users"
).select(
    "band_id",
    "user1",
    explode("users").alias("user2")
).filter("user1 < user2")

In [ ]:
df_pairs.show()

In [ ]:
candidate_pairs = df_pairs.select("user1", "user2").distinct()

In [ ]:
print("Candidate pairs:", candidate_pairs.count())

In [ ]:
candidate_pairs.coalesce(1).write \
    .mode("append") \
    .parquet(f"{BASE_DIR}/ml-25m-output/candidate_pairs_parquet")

print(f"Saved {candidate_pairs.count()} candidate pairs to {BASE_DIR}/ml-25m-output/candidate_pairs_parquet")

In [ ]:
candidate_pairs.coalesce(1).write \
    .mode("append") \
    .option("header", True) \
    .csv(f"{BASE_DIR}/ml-25m-output/candidate_pairs_csv")

print(f"Saved {candidate_pairs.count()} candidate pairs to {BASE_DIR}/ml-25m-output/candidate_pairs_csv")

In [ ]:
candidate_pairs.show()

In [ ]:
# Join with user shingles
# pairs_with_data = candidate_pairs \
#     .join(user_shingles.withColumnRenamed("userId", "user1"), "user1") \
#     .join(user_shingles.withColumnRenamed("userId", "user2"), "user2")

# Then compute Jaccard (can show if you want)

# Clustering

In [8]:
candidate_pairs = spark.read.csv(
    f"{BASE_DIR}/ml-25m-output/candidate_pairs_csv",
    header=True,
    inferSchema=True
)

In [9]:
candidate_pairs.show(5)

+-----+------+
|user1| user2|
+-----+------+
|72352|106491|
|21096| 25775|
|80597|125514|
|21456|147877|
|21731| 61892|
+-----+------+
only showing top 5 rows

In [10]:
from pyspark.sql.functions import col

edges1 = candidate_pairs.select(
    col("user1").alias("user"),
    col("user2").alias("neighbor")
)

edges2 = candidate_pairs.select(
    col("user2").alias("user"),
    col("user1").alias("neighbor")
)

edges = edges1.union(edges2)

In [11]:
edges1.show(5)

+-----+--------+
| user|neighbor|
+-----+--------+
|72352|  106491|
|21096|   25775|
|80597|  125514|
|21456|  147877|
|21731|   61892|
+-----+--------+
only showing top 5 rows

In [12]:
edges2.show(5)

+------+--------+
|  user|neighbor|
+------+--------+
|106491|   72352|
| 25775|   21096|
|125514|   80597|
|147877|   21456|
| 61892|   21731|
+------+--------+
only showing top 5 rows

In [13]:
from pyspark.sql.window import Window
from pyspark.sql.functions import row_number, col

window = Window.partitionBy("user").orderBy(col("neighbor"))

limited_neighbors = edges.withColumn(
    "rank",
    row_number().over(window)
).filter(col("rank") <= 100)

In [14]:
limited_neighbors.show(5)

+----+--------+----+
|user|neighbor|rank|
+----+--------+----+
|   3|     598|   1|
|   3|    4310|   2|
|   3|    4758|   3|
|   3|    4802|   4|
|   3|    6836|   5|
+----+--------+----+
only showing top 5 rows

In [15]:
from pyspark.sql.functions import collect_list

user_neighbors = limited_neighbors.groupBy("user").agg(
    collect_list("neighbor").alias("neighbors")
)

In [16]:
user_neighbors.show(20, truncate=False)

+----+-----------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------+
|user|neighbors                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                |
+----+-----------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------+
|3   |[598, 4310, 4758, 4802, 6836, 7439, 9808, 11052, 15281, 15539, 17532, 18434, 18602, 20202, 20302, 24557, 25082, 25212, 27787, 28551, 28661, 29420, 30200, 31279, 31881, 33576, 33583, 38588, 38896, 39612, 43657, 44371, 44862, 45870, 46088, 47824, 47976, 48265, 49931, 50449, 50535, 51328, 53289, 54573, 57814, 58887, 60915, 61524, 63257, 63903, 64018, 65073, 66351, 67287, 67598, 69502, 69546, 69688, 69784, 72954, 75156, 76188, 76223, 77192, 78992, 82788, 83665, 84457, 84801, 86187, 86570, 90234, 91040, 92972, 93265, 94846, 98091, 98273, 98771, 101398, 103514, 103600, 104219, 104484, 106024, 106632, 107787, 108000, 108053, 108573, 108863, 116442, 117444, 120220, 120451, 122913, 123431, 123856, 123887, 124386]|
|5   |[20207, 76171, 84981, 94299, 103789, 120123, 126809, 148806, 149780, 154789, 159960]                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                     |
|6   |[30104, 39234, 149494]                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                   |
|9   |[1513, 3256, 5250, 7004, 20739, 26830, 31176, 31405, 31861, 35913, 36290, 43351, 44906, 50660, 68972, 78300, 83503, 94556, 103603, 126014, 139178]                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                       |
|12  |[1894, 31932, 64441, 67770, 127157, 147091]                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                              |
|13  |[26399, 42926, 53014, 54036, 56666, 60970, 62259, 72722, 150552]                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                         |
|15  |[5078]                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                   |
|16  |[101617]                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                 |
|17  |[18207, 86227, 154916]                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                   |
|19  |[4060, 33820, 98694, 138024, 155206]                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                     |
|22  |[74, 140, 165, 168, 250, 306, 311, 352, 457, 518, 654, 940, 1022, 1169, 1205, 1225, 1237, 1291, 1410, 1603, 2124, 2149, 2296, 2466, 2668, 2736, 2874, 3017, 3170, 3203, 3466, 3486, 3521, 3707, 3947, 4054, 4123, 4489, 4538, 4603, 4667, 4718, 4733, 4847, 4963, 4990, 5008, 5050, 5121, 5154, 5158, 5212, 5272, 5290, 5311, 5369, 5411, 5437, 5484, 5626, 5664, 5723, 5772, 5906, 5920, 5959, 5977, 6008, 6049, 6101, 6133, 6161, 6194, 6450, 6737, 6802, 6974, 7098, 7142, 7209, 7219, 7392, 7514, 7569, 7722, 7817, 7825, 7944, 7954, 8030, 8200, 8259, 8386, 8389, 8411, 8444, 8493, 8498, 8558, 8571]                                                                                                                              |
|26  |[65477, 84368]                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                           |
|28  |[23168, 55859, 63338, 72097, 78218, 115921, 130586, 132370, 151690, 153053, 155783, 157769]                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                              |
|31  |[13020, 14344, 23868, 39871, 55921, 65515, 73614, 90906, 97291, 117105, 123720, 125786, 134642, 135723, 147912, 150922, 157267]                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                          |
|37  |[862, 1650, 3656, 5766, 6227, 7641, 7962, 8699, 9424, 11436, 13111, 13163, 13839, 16563, 16653, 17042, 17204, 20194, 21672, 21959, 22449, 22753, 25415, 25581, 25731, 25862, 27566, 29094, 29909, 30027, 31142, 32223, 33786, 36254, 36983, 37392, 38966, 40756, 40844, 42081, 42660, 43737, 44458, 45741, 47444, 48821, 48830, 52793, 54014, 54216, 54669, 55169, 55650, 56894, 57910, 62942, 65947, 67011, 67270, 67381, 70512, 73450, 78025, 78261, 78559, 78825, 78826, 81717, 82100, 83130, 83895, 84764, 85063, 85666, 87711, 88373, 89574, 90560, 90806, 93999, 97371, 100565, 101518, 105843, 106308, 108663, 110330, 111384, 111624, 112961, 114156, 114628, 118332, 118487, 119789, 119795, 122735, 124427, 124935, 125203]    |
|40  |[12137, 31499, 71396, 115616, 119099, 143307, 154648, 155055]                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                            |
|41  |[6970, 7201, 7932, 11358, 11714, 28487, 34223, 37978, 49985, 54702, 57115, 58208, 64319, 67344, 74046, 89727, 92844, 116588, 139447, 145909, 154956, 155748, 157908, 160939]                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                             |
|43  |[431, 5707, 9718, 11977, 14120, 15433, 20639, 23626, 24575, 27751, 28074, 30855, 37292, 37309, 54082, 55637, 62733, 62893, 65883, 66418, 68284, 70590, 71783, 72681, 73883, 74419, 75549, 84574, 86233, 91677, 101869, 119657, 120679, 124181, 124808, 127153, 138613, 140918, 146084, 153637, 155825, 158693]                                                                                                                                                                                                                                                                                                                                                                                                                           |
|47  |[958, 13202, 16427, 32466, 45778, 47614, 52054, 56503, 59849, 71294, 98319, 121443, 136317, 146970, 151097]                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                              |
|48  |[61372, 68301, 77448, 103026, 111002, 120049, 126715, 131309, 145054]                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                    |
+----+-----------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------+
only showing top 20 rows

to be contd

In [17]:
from pyspark.sql.functions import explode

pairs = user_neighbors.select(
    col("user"),
    explode("neighbors").alias("neighbor")
)

In [18]:
pairs.show(6)

+----+--------+
|user|neighbor|
+----+--------+
|   3|     598|
|   3|    4310|
|   3|    4758|
|   3|    4802|
|   3|    6836|
|   3|    7439|
+----+--------+
only showing top 6 rows

In [19]:
ratings1 = ratings.select(
    col("userId").alias("user"),
    col("movieId"),
    col("rating").alias("rating_user")
)

ratings2 = ratings.select(
    col("userId").alias("neighbor"),
    col("movieId"),
    col("rating").alias("rating_neighbor")
)

In [20]:
ratings1.show(5)

+----+-------+-----------+
|user|movieId|rating_user|
+----+-------+-----------+
|   1|    296|        5.0|
|   1|    306|        3.5|
|   1|    307|        5.0|
|   1|    665|        5.0|
|   1|    899|        3.5|
+----+-------+-----------+
only showing top 5 rows

In [21]:
ratings2.show(5)

+--------+-------+---------------+
|neighbor|movieId|rating_neighbor|
+--------+-------+---------------+
|       1|    296|            5.0|
|       1|    306|            3.5|
|       1|    307|            5.0|
|       1|    665|            5.0|
|       1|    899|            3.5|
+--------+-------+---------------+
only showing top 5 rows

In [22]:
joined = pairs \
    .join(ratings1, "user") \
    .join(ratings2, ["neighbor", "movieId"])

In [23]:
from pyspark.sql.functions import col

joined = joined.filter(
    (col("rating_user") > 0) & (col("rating_neighbor") > 0)
)

In [24]:
from pyspark.sql.functions import avg

means = joined.groupBy("user", "neighbor").agg(
    avg("rating_user").alias("mean_user"),
    avg("rating_neighbor").alias("mean_neighbor")
)

In [25]:
joined = joined.join(means, ["user", "neighbor"])

from pyspark.sql.functions import pow

centered = joined.withColumn(
    "ru_centered",
    col("rating_user") - col("mean_user")
).withColumn(
    "rv_centered",
    col("rating_neighbor") - col("mean_neighbor")
)

In [26]:
from pyspark.sql.functions import sum as spark_sum, sqrt

pearson = centered.groupBy("user", "neighbor").agg(
    spark_sum(col("ru_centered") * col("rv_centered")).alias("numerator"),
    sqrt(spark_sum(pow(col("ru_centered"), 2))).alias("denom_u"),
    sqrt(spark_sum(pow(col("rv_centered"), 2))).alias("denom_v")
)

In [27]:
from pyspark import StorageLevel
from pyspark.sql.functions import when

pearson = pearson.withColumn(
    "pearson",
    when(
        (col("denom_u") * col("denom_v")) != 0,
        col("numerator") / (col("denom_u") * col("denom_v"))
    ).otherwise(0)
)

pearson = pearson.persist(StorageLevel.MEMORY_AND_DISK)

In [28]:
from pyspark.sql.window import Window
from pyspark.sql.functions import row_number

window = Window.partitionBy("user").orderBy(col("pearson").desc())

top_neighbors = pearson.withColumn(
    "rank",
    row_number().over(window)
)

In [29]:
top_neighbors = top_neighbors.filter(col("rank") <= 10)

In [ ]:
# top_neighbors.show(5)

+----+--------+------------------+-----------------+------------------+-------------------+----+
|user|neighbor|         numerator|          denom_u|           denom_v|            pearson|rank|
+----+--------+------------------+-----------------+------------------+-------------------+----+
|   3|   54573|38.321256038647306|8.053414674701989| 8.519939670013885| 0.5584999699247678|   1|
|   3|  103514| 49.63484848484851|7.368442128017251|13.824330769050665| 0.4872668959011266|   2|
|   3|   11052| 55.01815642458089|10.27312080982133|11.146936347899995|0.48044991091410016|   3|
|   3|   15539| 73.45639534883716|9.771666445201593|15.664264618759203|0.47990024070057924|   4|
|   3|    4802| 48.32429718875498|7.749983806175583| 13.09610751820993|0.47612668161263194|   5|
+----+--------+------------------+-----------------+------------------+-------------------+----+
only showing top 5 rows

In [30]:
from pyspark.sql.functions import collect_list

final_neighbors = top_neighbors.groupBy("user").agg(
    collect_list("neighbor").alias("neighbors")
)

In [31]:
final_neighbors.show(5)

ERROR:root:KeyboardInterrupt while sending command.
Traceback (most recent call last):
  File "/usr/local/lib/python3.12/dist-packages/py4j/java_gateway.py", line 1038, in send_command
    response = connection.send_command(command)
               ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/usr/local/lib/python3.12/dist-packages/py4j/clientserver.py", line 535, in send_command
    answer = smart_decode(self.stream.readline()[:-1])
                          ^^^^^^^^^^^^^^^^^^^^^^
  File "/usr/lib/python3.12/socket.py", line 720, in readinto
    return self._sock.recv_into(b)
           ^^^^^^^^^^^^^^^^^^^^^^^
KeyboardInterrupt

KeyboardInterrupt:

SAVE TOP(FINAL) NEIGHBOURS SORTED ON SIMILARITY AS PARQUET

In [ ]:

from pyspark import StorageLevel

final_neighbors = final_neighbors.persist(StorageLevel.MEMORY_AND_DISK)

final_neighbors.write \
    .mode("overwrite") \
    .parquet("/content/final_neighbors_parquet")

print("write done in parquet format")

ERROR:root:KeyboardInterrupt while sending command.
Traceback (most recent call last):
  File "/usr/local/lib/python3.12/dist-packages/py4j/java_gateway.py", line 1038, in send_command
    response = connection.send_command(command)
               ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/usr/local/lib/python3.12/dist-packages/py4j/clientserver.py", line 535, in send_command
    answer = smart_decode(self.stream.readline()[:-1])
                          ^^^^^^^^^^^^^^^^^^^^^^
  File "/usr/lib/python3.12/socket.py", line 720, in readinto
    return self._sock.recv_into(b)
           ^^^^^^^^^^^^^^^^^^^^^^^
KeyboardInterrupt

KeyboardInterrupt:

SAVE TOP NEIGHBOURS SORTED ON SIMILARITY AS CSV

In [ ]:
from pyspark.sql.functions import concat_ws

final_neighbors_csv = final_neighbors.withColumn(
    "neighbors",
    concat_ws(",", "neighbors")
)

In [ ]:
final_neighbors_csv.write \
    .mode("overwrite") \
    .option("header", True) \
    .csv(f"{BASE_DIR}/ml-25m-output/final_neighbors_csv")

print("Saved CSV successfully ✅")

NameError: name 'final_neighbors_csv' is not defined

In [ ]:
final_neighbors.show(10, truncate=False)

ERROR:root:KeyboardInterrupt while sending command.
Traceback (most recent call last):
  File "/usr/local/lib/python3.12/dist-packages/py4j/java_gateway.py", line 1038, in send_command
    response = connection.send_command(command)
               ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/usr/local/lib/python3.12/dist-packages/py4j/clientserver.py", line 535, in send_command
    answer = smart_decode(self.stream.readline()[:-1])
                          ^^^^^^^^^^^^^^^^^^^^^^
  File "/usr/lib/python3.12/socket.py", line 720, in readinto
    return self._sock.recv_into(b)
           ^^^^^^^^^^^^^^^^^^^^^^^
KeyboardInterrupt

KeyboardInterrupt:

In [32]:
final_neighbors.take(3)

ERROR:root:KeyboardInterrupt while sending command.
Traceback (most recent call last):
  File "/usr/local/lib/python3.12/dist-packages/py4j/java_gateway.py", line 1038, in send_command
    response = connection.send_command(command)
               ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/usr/local/lib/python3.12/dist-packages/py4j/clientserver.py", line 535, in send_command
    answer = smart_decode(self.stream.readline()[:-1])
                          ^^^^^^^^^^^^^^^^^^^^^^
  File "/usr/lib/python3.12/socket.py", line 720, in readinto
    return self._sock.recv_into(b)
           ^^^^^^^^^^^^^^^^^^^^^^^
KeyboardInterrupt

KeyboardInterrupt:

Checking if sorting is correct

In [33]:
u = 148

In [34]:
neighbors = final_neighbors.filter(col("user") == u).collect()[0]["neighbors"]
print(neighbors)

ERROR:root:KeyboardInterrupt while sending command.
Traceback (most recent call last):
  File "/usr/local/lib/python3.12/dist-packages/py4j/java_gateway.py", line 1038, in send_command
    response = connection.send_command(command)
               ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/usr/local/lib/python3.12/dist-packages/py4j/clientserver.py", line 535, in send_command
    answer = smart_decode(self.stream.readline()[:-1])
                          ^^^^^^^^^^^^^^^^^^^^^^
  File "/usr/lib/python3.12/socket.py", line 720, in readinto
    return self._sock.recv_into(b)
           ^^^^^^^^^^^^^^^^^^^^^^^
KeyboardInterrupt

KeyboardInterrupt:

In [ ]:
pearson_u = pearson.filter(col("user") == u) \
    .select("neighbor", "pearson")

In [ ]:
pearson_top = pearson_u.filter(col("neighbor").isin(neighbors))

In [ ]:
pearson_sorted = pearson_top.orderBy(col("pearson").desc())

pearson_sorted.show(truncate=False)

# **CONTENT BASED FILTERING**

In [45]:
import pandas as pd
import ast

movies = pd.read_csv(f"{BASE_DIR}/tmdb-5000/tmdb_5000_movies.csv")
credits = pd.read_csv(f"{BASE_DIR}/tmdb-5000/tmdb_5000_credits.csv")

# merged the datasets
movies = movies.merge(credits, on="title")

In [46]:
movies.columns

Index(['budget', 'genres', 'homepage', 'id', 'keywords', 'original_language',
       'original_title', 'overview', 'popularity', 'production_companies',
       'production_countries', 'release_date', 'revenue', 'runtime',
       'spoken_languages', 'status', 'tagline', 'title', 'vote_average',
       'vote_count', 'movie_id', 'cast', 'crew'],
      dtype='object')

In [47]:
movies["genres"][0]

'[{"id": 28, "name": "Action"}, {"id": 12, "name": "Adventure"}, {"id": 14, "name": "Fantasy"}, {"id": 878, "name": "Science Fiction"}]'

In [48]:
movies["keywords"][0]

'[{"id": 1463, "name": "culture clash"}, {"id": 2964, "name": "future"}, {"id": 3386, "name": "space war"}, {"id": 3388, "name": "space colony"}, {"id": 3679, "name": "society"}, {"id": 3801, "name": "space travel"}, {"id": 9685, "name": "futuristic"}, {"id": 9840, "name": "romance"}, {"id": 9882, "name": "space"}, {"id": 9951, "name": "alien"}, {"id": 10148, "name": "tribe"}, {"id": 10158, "name": "alien planet"}, {"id": 10987, "name": "cgi"}, {"id": 11399, "name": "marine"}, {"id": 13065, "name": "soldier"}, {"id": 14643, "name": "battle"}, {"id": 14720, "name": "love affair"}, {"id": 165431, "name": "anti war"}, {"id": 193554, "name": "power relations"}, {"id": 206690, "name": "mind and soul"}, {"id": 209714, "name": "3d"}]'

In [49]:
movies["cast"][0]

'[{"cast_id": 242, "character": "Jake Sully", "credit_id": "5602a8a7c3a3685532001c9a", "gender": 2, "id": 65731, "name": "Sam Worthington", "order": 0}, {"cast_id": 3, "character": "Neytiri", "credit_id": "52fe48009251416c750ac9cb", "gender": 1, "id": 8691, "name": "Zoe Saldana", "order": 1}, {"cast_id": 25, "character": "Dr. Grace Augustine", "credit_id": "52fe48009251416c750aca39", "gender": 1, "id": 10205, "name": "Sigourney Weaver", "order": 2}, {"cast_id": 4, "character": "Col. Quaritch", "credit_id": "52fe48009251416c750ac9cf", "gender": 2, "id": 32747, "name": "Stephen Lang", "order": 3}, {"cast_id": 5, "character": "Trudy Chacon", "credit_id": "52fe48009251416c750ac9d3", "gender": 1, "id": 17647, "name": "Michelle Rodriguez", "order": 4}, {"cast_id": 8, "character": "Selfridge", "credit_id": "52fe48009251416c750ac9e1", "gender": 2, "id": 1771, "name": "Giovanni Ribisi", "order": 5}, {"cast_id": 7, "character": "Norm Spellman", "credit_id": "52fe48009251416c750ac9dd", "gender": 2, "id": 59231, "name": "Joel David Moore", "order": 6}, {"cast_id": 9, "character": "Moat", "credit_id": "52fe48009251416c750ac9e5", "gender": 1, "id": 30485, "name": "CCH Pounder", "order": 7}, {"cast_id": 11, "character": "Eytukan", "credit_id": "52fe48009251416c750ac9ed", "gender": 2, "id": 15853, "name": "Wes Studi", "order": 8}, {"cast_id": 10, "character": "Tsu\'Tey", "credit_id": "52fe48009251416c750ac9e9", "gender": 2, "id": 10964, "name": "Laz Alonso", "order": 9}, {"cast_id": 12, "character": "Dr. Max Patel", "credit_id": "52fe48009251416c750ac9f1", "gender": 2, "id": 95697, "name": "Dileep Rao", "order": 10}, {"cast_id": 13, "character": "Lyle Wainfleet", "credit_id": "52fe48009251416c750ac9f5", "gender": 2, "id": 98215, "name": "Matt Gerald", "order": 11}, {"cast_id": 32, "character": "Private Fike", "credit_id": "52fe48009251416c750aca5b", "gender": 2, "id": 154153, "name": "Sean Anthony Moran", "order": 12}, {"cast_id": 33, "character": "Cryo Vault Med Tech", "credit_id": "52fe48009251416c750aca5f", "gender": 2, "id": 397312, "name": "Jason Whyte", "order": 13}, {"cast_id": 34, "character": "Venture Star Crew Chief", "credit_id": "52fe48009251416c750aca63", "gender": 2, "id": 42317, "name": "Scott Lawrence", "order": 14}, {"cast_id": 35, "character": "Lock Up Trooper", "credit_id": "52fe48009251416c750aca67", "gender": 2, "id": 986734, "name": "Kelly Kilgour", "order": 15}, {"cast_id": 36, "character": "Shuttle Pilot", "credit_id": "52fe48009251416c750aca6b", "gender": 0, "id": 1207227, "name": "James Patrick Pitt", "order": 16}, {"cast_id": 37, "character": "Shuttle Co-Pilot", "credit_id": "52fe48009251416c750aca6f", "gender": 0, "id": 1180936, "name": "Sean Patrick Murphy", "order": 17}, {"cast_id": 38, "character": "Shuttle Crew Chief", "credit_id": "52fe48009251416c750aca73", "gender": 2, "id": 1019578, "name": "Peter Dillon", "order": 18}, {"cast_id": 39, "character": "Tractor Operator / Troupe", "credit_id": "52fe48009251416c750aca77", "gender": 0, "id": 91443, "name": "Kevin Dorman", "order": 19}, {"cast_id": 40, "character": "Dragon Gunship Pilot", "credit_id": "52fe48009251416c750aca7b", "gender": 2, "id": 173391, "name": "Kelson Henderson", "order": 20}, {"cast_id": 41, "character": "Dragon Gunship Gunner", "credit_id": "52fe48009251416c750aca7f", "gender": 0, "id": 1207236, "name": "David Van Horn", "order": 21}, {"cast_id": 42, "character": "Dragon Gunship Navigator", "credit_id": "52fe48009251416c750aca83", "gender": 0, "id": 215913, "name": "Jacob Tomuri", "order": 22}, {"cast_id": 43, "character": "Suit #1", "credit_id": "52fe48009251416c750aca87", "gender": 0, "id": 143206, "name": "Michael Blain-Rozgay", "order": 23}, {"cast_id": 44, "character": "Suit #2", "credit_id": "52fe48009251416c750aca8b", "gender": 2, "id": 169676, "name": "Jon Curry", "order": 24}, {"cast_id": 46, "character": "Ambient Room Tech", "credit_id": "52fe48009251416c750aca8f", "gender": 0, "id": 1048610, "name": "Luke Hawker", "order": 25}, {"cast_id": 47, "character": "Ambient Room Tech / Troupe", "credit_id": "52fe48009251416c750aca93", "gender": 0, "id": 42288, "name": "Woody Schultz", "order": 26}, {"cast_id": 48, "character": "Horse Clan Leader", "credit_id": "52fe48009251416c750aca97", "gender": 2, "id": 68278, "name": "Peter Mensah", "order": 27}, {"cast_id": 49, "character": "Link Room Tech", "credit_id": "52fe48009251416c750aca9b", "gender": 0, "id": 1207247, "name": "Sonia Yee", "order": 28}, {"cast_id": 50, "character": "Basketball Avatar / Troupe", "credit_id": "52fe48009251416c750aca9f", "gender": 1, "id": 1207248, "name": "Jahnel Curfman", "order": 29}, {"cast_id": 51, "character": "Basketball Avatar", "credit_id": "52fe48009251416c750acaa3", "gender": 0, "id": 89714, "name": "Ilram Choi", "order": 30}, {"cast_id": 52, "character": "Na\'vi Child", "credit_id": "52fe48009251416c750acaa7", "gender": 0, "id": 1207249, "name": "Kyla Warren", "order": 31}, {"cast_id": 53, "character": "Troupe", "credit_id": "52fe48009251416c750acaab", "gender": 0, "id": 1207250, "name": "Lisa Roumain", "order": 32}, {"cast_id": 54, "character": "Troupe", "credit_id": "52fe48009251416c750acaaf", "gender": 1, "id": 83105, "name": "Debra Wilson", "order": 33}, {"cast_id": 57, "character": "Troupe", "credit_id": "52fe48009251416c750acabb", "gender": 0, "id": 1207253, "name": "Chris Mala", "order": 34}, {"cast_id": 55, "character": "Troupe", "credit_id": "52fe48009251416c750acab3", "gender": 0, "id": 1207251, "name": "Taylor Kibby", "order": 35}, {"cast_id": 56, "character": "Troupe", "credit_id": "52fe48009251416c750acab7", "gender": 0, "id": 1207252, "name": "Jodie Landau", "order": 36}, {"cast_id": 58, "character": "Troupe", "credit_id": "52fe48009251416c750acabf", "gender": 0, "id": 1207254, "name": "Julie Lamm", "order": 37}, {"cast_id": 59, "character": "Troupe", "credit_id": "52fe48009251416c750acac3", "gender": 0, "id": 1207257, "name": "Cullen B. Madden", "order": 38}, {"cast_id": 60, "character": "Troupe", "credit_id": "52fe48009251416c750acac7", "gender": 0, "id": 1207259, "name": "Joseph Brady Madden", "order": 39}, {"cast_id": 61, "character": "Troupe", "credit_id": "52fe48009251416c750acacb", "gender": 0, "id": 1207262, "name": "Frankie Torres", "order": 40}, {"cast_id": 62, "character": "Troupe", "credit_id": "52fe48009251416c750acacf", "gender": 1, "id": 1158600, "name": "Austin Wilson", "order": 41}, {"cast_id": 63, "character": "Troupe", "credit_id": "52fe48019251416c750acad3", "gender": 1, "id": 983705, "name": "Sara Wilson", "order": 42}, {"cast_id": 64, "character": "Troupe", "credit_id": "52fe48019251416c750acad7", "gender": 0, "id": 1207263, "name": "Tamica Washington-Miller", "order": 43}, {"cast_id": 65, "character": "Op Center Staff", "credit_id": "52fe48019251416c750acadb", "gender": 1, "id": 1145098, "name": "Lucy Briant", "order": 44}, {"cast_id": 66, "character": "Op Center Staff", "credit_id": "52fe48019251416c750acadf", "gender": 2, "id": 33305, "name": "Nathan Meister", "order": 45}, {"cast_id": 67, "character": "Op Center Staff", "credit_id": "52fe48019251416c750acae3", "gender": 0, "id": 1207264, "name": "Gerry Blair", "order": 46}, {"cast_id": 68, "character": "Op Center Staff", "credit_id": "52fe48019251416c750acae7", "gender": 2, "id": 33311, "name": "Matthew Chamberlain", "order": 47}, {"cast_id": 69, "character": "Op Center Staff", "credit_id": "52fe48019251416c750acaeb", "gender": 0, "id": 1207265, "name": "Paul Yates", "order": 48}, {"cast_id": 70, "character": "Op Center Duty Officer", "credit_id": "52fe48019251416c750acaef", "gender": 0, "id": 1207266, "name": "Wray Wilson", "order": 49}, {"cast_id": 71, "character": "Op Center Staff", "credit_id": "52fe48019251416c750acaf3", "gender": 2, "id": 54492, "name": "James Gaylyn", "order": 50}, {"cast_id": 72, "character": "Dancer", "credit_id": "52fe48019251416c750acaf7", "gender": 0, "id": 1207267, "name": "Melvin Leno Clark III", "order": 51}, {"cast_id": 73, "character": "Dancer", "credit_id": "52fe48019251416c750acafb", "gender": 0, "id": 1207268, "name": "Carvon Futrell", "order": 52}, {"cast_id": 74, "character": "Dancer", "credit_id": "52fe48019251416c750acaff", "gender": 0, "id": 1207269, "name": "Brandon Jelkes", "order": 53}, {"cast_id": 75, "character": "Dancer", "credit_id": "52fe48019251416c750acb03", "gender": 0, "id": 1207270, "name": "Micah Moch", "order": 54}, {"cast_id": 76, "character": "Dancer", "credit_id": "52fe48019251416c750acb07", "gender": 0, "id": 1207271, "name": "Hanniyah Muhammad", "order": 55}, {"cast_id": 77, "character": "Dancer", "credit_id": "52fe48019251416c750acb0b", "gender": 0, "id": 1207272, "name": "Christopher Nolen", "order": 56}, {"cast_id": 78, "character": "Dancer", "credit_id": "52fe48019251416c750acb0f", "gender": 0, "id": 1207273, "name": "Christa Oliver", "order": 57}, {"cast_id": 79, "character": "Dancer", "credit_id": "52fe48019251416c750acb13", "gender": 0, "id": 1207274, "name": "April Marie Thomas", "order": 58}, {"cast_id": 80, "character": "Dancer", "credit_id": "52fe48019251416c750acb17", "gender": 0, "id": 1207275, "name": "Bravita A. Threatt", "order": 59}, {"cast_id": 81, "character": "Mining Chief (uncredited)", "credit_id": "52fe48019251416c750acb1b", "gender": 0, "id": 1207276, "name": "Colin Bleasdale", "order": 60}, {"cast_id": 82, "character": "Veteran Miner (uncredited)", "credit_id": "52fe48019251416c750acb1f", "gender": 0, "id": 107969, "name": "Mike Bodnar", "order": 61}, {"cast_id": 83, "character": "Richard (uncredited)", "credit_id": "52fe48019251416c750acb23", "gender": 0, "id": 1207278, "name": "Matt Clayton", "order": 62}, {"cast_id": 84, "character": "Nav\'i (uncredited)", "credit_id": "52fe48019251416c750acb27", "gender": 1, "id": 147898, "name": "Nicole Dionne", "order": 63}, {"cast_id": 85, "character": "Trooper (uncredited)", "credit_id": "52fe48019251416c750acb2b", "gender": 0, "id": 1207280, "name": "Jamie Harrison", "order": 64}, {"cast_id": 86, "character": "Trooper (uncredited)", "credit_id": "52fe48019251416c750acb2f", "gender": 0, "id": 1207281, "name": "Allan Henry", "order": 65}, {"cast_id": 87, "character": "Ground Technician (uncredited)", "credit_id": "52fe48019251416c750acb33", "gender": 2, "id": 1207282, "name": "Anthony Ingruber", "order": 66}, {"cast_id": 88, "character": "Flight Crew Mechanic (uncredited)", "credit_id": "52fe48019251416c750acb37", "gender": 0, "id": 1207283, "name": "Ashley Jeffery", "order": 67}, {"cast_id": 14, "character": "Samson Pilot", "credit_id": "52fe48009251416c750ac9f9", "gender": 0, "id": 98216, "name": "Dean Knowsley", "order": 68}, {"cast_id": 89, "character": "Trooper (uncredited)", "credit_id": "52fe48019251416c750acb3b", "gender": 0, "id": 1201399, "name": "Joseph Mika-Hunt", "order": 69}, {"cast_id": 90, "character": "Banshee (uncredited)", "credit_id": "52fe48019251416c750acb3f", "gender": 0, "id": 236696, "name": "Terry Notary", "order": 70}, {"cast_id": 91, "character": "Soldier (uncredited)", "credit_id": "52fe48019251416c750acb43", "gender": 0, "id": 1207287, "name": "Kai Pantano", "order": 71}, {"cast_id": 92, "character": "Blast Technician (uncredited)", "credit_id": "52fe48019251416c750acb47", "gender": 0, "id": 1207288, "name": "Logan Pithyou", "order": 72}, {"cast_id": 93, "character": "Vindum Raah (uncredited)", "credit_id": "52fe48019251416c750acb4b", "gender": 0, "id": 1207289, "name": "Stuart Pollock", "order": 73}, {"cast_id": 94, "character": "Hero (uncredited)", "credit_id": "52fe48019251416c750acb4f", "gender": 0, "id": 584868, "name": "Raja", "order": 74}, {"cast_id": 95, "character": "Ops Centreworker (uncredited)", "credit_id": "52fe48019251416c750acb53", "gender": 0, "id": 1207290, "name": "Gareth Ruck", "order": 75}, {"cast_id": 96, "character": "Engineer (uncredited)", "credit_id": "52fe48019251416c750acb57", "gender": 0, "id": 1062463, "name": "Rhian Sheehan", "order": 76}, {"cast_id": 97, "character": "Col. Quaritch\'s Mech Suit (uncredited)", "credit_id": "52fe48019251416c750acb5b", "gender": 0, "id": 60656, "name": "T. J. Storm", "order": 77}, {"cast_id": 98, "character": "Female Marine (uncredited)", "credit_id": "52fe48019251416c750acb5f", "gender": 0, "id": 1207291, "name": "Jodie Taylor", "order": 78}, {"cast_id": 99, "character": "Ikran Clan Leader (uncredited)", "credit_id": "52fe48019251416c750acb63", "gender": 1, "id": 1186027, "name": "Alicia Vela-Bailey", "order": 79}, {"cast_id": 100, "character": "Geologist (uncredited)", "credit_id": "52fe48019251416c750acb67", "gender": 0, "id": 1207292, "name": "Richard Whiteside", "order": 80}, {"cast_id": 101, "character": "Na\'vi (uncredited)", "credit_id": "52fe48019251416c750acb6b", "gender": 0, "id": 103259, "name": "Nikie Zambo", "order": 81}, {"cast_id": 102, "character": "Ambient Room Tech / Troupe", "credit_id": "52fe48019251416c750acb6f", "gender": 1, "id": 42286, "name": "Julene Renee", "order": 82}]'

In [50]:
movies["crew"][0]

'[{"credit_id": "52fe48009251416c750aca23", "department": "Editing", "gender": 0, "id": 1721, "job": "Editor", "name": "Stephen E. Rivkin"}, {"credit_id": "539c47ecc3a36810e3001f87", "department": "Art", "gender": 2, "id": 496, "job": "Production Design", "name": "Rick Carter"}, {"credit_id": "54491c89c3a3680fb4001cf7", "department": "Sound", "gender": 0, "id": 900, "job": "Sound Designer", "name": "Christopher Boyes"}, {"credit_id": "54491cb70e0a267480001bd0", "department": "Sound", "gender": 0, "id": 900, "job": "Supervising Sound Editor", "name": "Christopher Boyes"}, {"credit_id": "539c4a4cc3a36810c9002101", "department": "Production", "gender": 1, "id": 1262, "job": "Casting", "name": "Mali Finn"}, {"credit_id": "5544ee3b925141499f0008fc", "department": "Sound", "gender": 2, "id": 1729, "job": "Original Music Composer", "name": "James Horner"}, {"credit_id": "52fe48009251416c750ac9c3", "department": "Directing", "gender": 2, "id": 2710, "job": "Director", "name": "James Cameron"}, {"credit_id": "52fe48009251416c750ac9d9", "department": "Writing", "gender": 2, "id": 2710, "job": "Writer", "name": "James Cameron"}, {"credit_id": "52fe48009251416c750aca17", "department": "Editing", "gender": 2, "id": 2710, "job": "Editor", "name": "James Cameron"}, {"credit_id": "52fe48009251416c750aca29", "department": "Production", "gender": 2, "id": 2710, "job": "Producer", "name": "James Cameron"}, {"credit_id": "52fe48009251416c750aca3f", "department": "Writing", "gender": 2, "id": 2710, "job": "Screenplay", "name": "James Cameron"}, {"credit_id": "539c4987c3a36810ba0021a4", "department": "Art", "gender": 2, "id": 7236, "job": "Art Direction", "name": "Andrew Menzies"}, {"credit_id": "549598c3c3a3686ae9004383", "department": "Visual Effects", "gender": 0, "id": 6690, "job": "Visual Effects Producer", "name": "Jill Brooks"}, {"credit_id": "52fe48009251416c750aca4b", "department": "Production", "gender": 1, "id": 6347, "job": "Casting", "name": "Margery Simkin"}, {"credit_id": "570b6f419251417da70032fe", "department": "Art", "gender": 2, "id": 6878, "job": "Supervising Art Director", "name": "Kevin Ishioka"}, {"credit_id": "5495a0fac3a3686ae9004468", "department": "Sound", "gender": 0, "id": 6883, "job": "Music Editor", "name": "Dick Bernstein"}, {"credit_id": "54959706c3a3686af3003e81", "department": "Sound", "gender": 0, "id": 8159, "job": "Sound Effects Editor", "name": "Shannon Mills"}, {"credit_id": "54491d58c3a3680fb1001ccb", "department": "Sound", "gender": 0, "id": 8160, "job": "Foley", "name": "Dennie Thorpe"}, {"credit_id": "54491d6cc3a3680fa5001b2c", "department": "Sound", "gender": 0, "id": 8163, "job": "Foley", "name": "Jana Vance"}, {"credit_id": "52fe48009251416c750aca57", "department": "Costume & Make-Up", "gender": 1, "id": 8527, "job": "Costume Design", "name": "Deborah Lynn Scott"}, {"credit_id": "52fe48009251416c750aca2f", "department": "Production", "gender": 2, "id": 8529, "job": "Producer", "name": "Jon Landau"}, {"credit_id": "539c4937c3a36810ba002194", "department": "Art", "gender": 0, "id": 9618, "job": "Art Direction", "name": "Sean Haworth"}, {"credit_id": "539c49b6c3a36810c10020e6", "department": "Art", "gender": 1, "id": 12653, "job": "Set Decoration", "name": "Kim Sinclair"}, {"credit_id": "570b6f2f9251413a0e00020d", "department": "Art", "gender": 1, "id": 12653, "job": "Supervising Art Director", "name": "Kim Sinclair"}, {"credit_id": "54491a6c0e0a26748c001b19", "department": "Art", "gender": 2, "id": 14350, "job": "Set Designer", "name": "Richard F. Mays"}, {"credit_id": "56928cf4c3a3684cff0025c4", "department": "Production", "gender": 1, "id": 20294, "job": "Executive Producer", "name": "Laeta Kalogridis"}, {"credit_id": "52fe48009251416c750aca51", "department": "Costume & Make-Up", "gender": 0, "id": 17675, "job": "Costume Design", "name": "Mayes C. Rubeo"}, {"credit_id": "52fe48009251416c750aca11", "department": "Camera", "gender": 2, "id": 18265, "job": "Director of Photography", "name": "Mauro Fiore"}, {"credit_id": "5449194d0e0a26748f001b39", "department": "Art", "gender": 0, "id": 42281, "job": "Set Designer", "name": "Scott Herbertson"}, {"credit_id": "52fe48009251416c750aca05", "department": "Crew", "gender": 0, "id": 42288, "job": "Stunts", "name": "Woody Schultz"}, {"credit_id": "5592aefb92514152de0010f5", "department": "Costume & Make-Up", "gender": 0, "id": 29067, "job": "Makeup Artist", "name": "Linda DeVetta"}, {"credit_id": "5592afa492514152de00112c", "department": "Costume & Make-Up", "gender": 0, "id": 29067, "job": "Hairstylist", "name": "Linda DeVetta"}, {"credit_id": "54959ed592514130fc002e5d", "department": "Camera", "gender": 2, "id": 33302, "job": "Camera Operator", "name": "Richard Bluck"}, {"credit_id": "539c4891c3a36810ba002147", "department": "Art", "gender": 2, "id": 33303, "job": "Art Direction", "name": "Simon Bright"}, {"credit_id": "54959c069251417a81001f3a", "department": "Visual Effects", "gender": 0, "id": 113145, "job": "Visual Effects Supervisor", "name": "Richard Martin"}, {"credit_id": "54959a0dc3a3680ff5002c8d", "department": "Crew", "gender": 2, "id": 58188, "job": "Visual Effects Editor", "name": "Steve R. Moore"}, {"credit_id": "52fe48009251416c750aca1d", "department": "Editing", "gender": 2, "id": 58871, "job": "Editor", "name": "John Refoua"}, {"credit_id": "54491a4dc3a3680fc30018ca", "department": "Art", "gender": 0, "id": 92359, "job": "Set Designer", "name": "Karl J. Martin"}, {"credit_id": "52fe48009251416c750aca35", "department": "Camera", "gender": 1, "id": 72201, "job": "Director of Photography", "name": "Chiling Lin"}, {"credit_id": "52fe48009251416c750ac9ff", "department": "Crew", "gender": 0, "id": 89714, "job": "Stunts", "name": "Ilram Choi"}, {"credit_id": "54959c529251416e2b004394", "department": "Visual Effects", "gender": 2, "id": 93214, "job": "Visual Effects Supervisor", "name": "Steven Quale"}, {"credit_id": "54491edf0e0a267489001c37", "department": "Crew", "gender": 1, "id": 122607, "job": "Dialect Coach", "name": "Carla Meyer"}, {"credit_id": "539c485bc3a368653d001a3a", "department": "Art", "gender": 2, "id": 132585, "job": "Art Direction", "name": "Nick Bassett"}, {"credit_id": "539c4903c3a368653d001a74", "department": "Art", "gender": 0, "id": 132596, "job": "Art Direction", "name": "Jill Cormack"}, {"credit_id": "539c4967c3a368653d001a94", "department": "Art", "gender": 0, "id": 132604, "job": "Art Direction", "name": "Andy McLaren"}, {"credit_id": "52fe48009251416c750aca45", "department": "Crew", "gender": 0, "id": 236696, "job": "Motion Capture Artist", "name": "Terry Notary"}, {"credit_id": "54959e02c3a3680fc60027d2", "department": "Crew", "gender": 2, "id": 956198, "job": "Stunt Coordinator", "name": "Garrett Warren"}, {"credit_id": "54959ca3c3a3686ae300438c", "department": "Visual Effects", "gender": 2, "id": 957874, "job": "Visual Effects Supervisor", "name": "Jonathan Rothbart"}, {"credit_id": "570b6f519251412c74001b2f", "department": "Art", "gender": 0, "id": 957889, "job": "Supervising Art Director", "name": "Stefan Dechant"}, {"credit_id": "570b6f62c3a3680b77007460", "department": "Art", "gender": 2, "id": 959555, "job": "Supervising Art Director", "name": "Todd Cherniawsky"}, {"credit_id": "539c4a3ac3a36810da0021cc", "department": "Production", "gender": 0, "id": 1016177, "job": "Casting", "name": "Miranda Rivers"}, {"credit_id": "539c482cc3a36810c1002062", "department": "Art", "gender": 0, "id": 1032536, "job": "Production Design", "name": "Robert Stromberg"}, {"credit_id": "539c4b65c3a36810c9002125", "department": "Costume & Make-Up", "gender": 2, "id": 1071680, "job": "Costume Design", "name": "John Harding"}, {"credit_id": "54959e6692514130fc002e4e", "department": "Camera", "gender": 0, "id": 1177364, "job": "Steadicam Operator", "name": "Roberto De Angelis"}, {"credit_id": "539c49f1c3a368653d001aac", "department": "Costume & Make-Up", "gender": 2, "id": 1202850, "job": "Makeup Department Head", "name": "Mike Smithson"}, {"credit_id": "5495999ec3a3686ae100460c", "department": "Visual Effects", "gender": 0, "id": 1204668, "job": "Visual Effects Producer", "name": "Alain Lalanne"}, {"credit_id": "54959cdfc3a3681153002729", "department": "Visual Effects", "gender": 0, "id": 1206410, "job": "Visual Effects Supervisor", "name": "Lucas Salton"}, {"credit_id": "549596239251417a81001eae", "department": "Crew", "gender": 0, "id": 1234266, "job": "Post Production Supervisor", "name": "Janace Tashjian"}, {"credit_id": "54959c859251416e1e003efe", "department": "Visual Effects", "gender": 0, "id": 1271932, "job": "Visual Effects Supervisor", "name": "Stephen Rosenbaum"}, {"credit_id": "5592af28c3a368775a00105f", "department": "Costume & Make-Up", "gender": 0, "id": 1310064, "job": "Makeup Artist", "name": "Frankie Karena"}, {"credit_id": "539c4adfc3a36810e300203b", "department": "Costume & Make-Up", "gender": 1, "id": 1319844, "job": "Costume Supervisor", "name": "Lisa Lovaas"}, {"credit_id": "54959b579251416e2b004371", "department": "Visual Effects", "gender": 0, "id": 1327028, "job": "Visual Effects Supervisor", "name": "Jonathan Fawkner"}, {"credit_id": "539c48a7c3a36810b5001fa7", "department": "Art", "gender": 0, "id": 1330561, "job": "Art Direction", "name": "Robert Bavin"}, {"credit_id": "539c4a71c3a36810da0021e0", "department": "Costume & Make-Up", "gender": 0, "id": 1330567, "job": "Costume Supervisor", "name": "Anthony Almaraz"}, {"credit_id": "539c4a8ac3a36810ba0021e4", "department": "Costume & Make-Up", "gender": 0, "id": 1330570, "job": "Costume Supervisor", "name": "Carolyn M. Fenton"}, {"credit_id": "539c4ab6c3a36810da0021f0", "department": "Costume & Make-Up", "gender": 0, "id": 1330574, "job": "Costume Supervisor", "name": "Beth Koenigsberg"}, {"credit_id": "54491ab70e0a267480001ba2", "department": "Art", "gender": 0, "id": 1336191, "job": "Set Designer", "name": "Sam Page"}, {"credit_id": "544919d9c3a3680fc30018bd", "department": "Art", "gender": 0, "id": 1339441, "job": "Set Designer", "name": "Tex Kadonaga"}, {"credit_id": "54491cf50e0a267483001b0c", "department": "Editing", "gender": 0, "id": 1352422, "job": "Dialogue Editor", "name": "Kim Foscato"}, {"credit_id": "544919f40e0a26748c001b09", "department": "Art", "gender": 0, "id": 1352962, "job": "Set Designer", "name": "Tammy S. Lee"}, {"credit_id": "5495a115c3a3680ff5002d71", "department": "Crew", "gender": 0, "id": 1357070, "job": "Transportation Coordinator", "name": "Denny Caira"}, {"credit_id": "5495a12f92514130fc002e94", "department": "Crew", "gender": 0, "id": 1357071, "job": "Transportation Coordinator", "name": "James Waitkus"}, {"credit_id": "5495976fc3a36811530026b0", "department": "Sound", "gender": 0, "id": 1360103, "job": "Supervising Sound Editor", "name": "Addison Teague"}, {"credit_id": "54491837c3a3680fb1001c5a", "department": "Art", "gender": 2, "id": 1376887, "job": "Set Designer", "name": "C. Scott Baker"}, {"credit_id": "54491878c3a3680fb4001c9d", "department": "Art", "gender": 0, "id": 1376888, "job": "Set Designer", "name": "Luke Caska"}, {"credit_id": "544918dac3a3680fa5001ae0", "department": "Art", "gender": 0, "id": 1376889, "job": "Set Designer", "name": "David Chow"}, {"credit_id": "544919110e0a267486001b68", "department": "Art", "gender": 0, "id": 1376890, "job": "Set Designer", "name": "Jonathan Dyer"}, {"credit_id": "54491967c3a3680faa001b5e", "department": "Art", "gender": 0, "id": 1376891, "job": "Set Designer", "name": "Joseph Hiura"}, {"credit_id": "54491997c3a3680fb1001c8a", "department": "Art", "gender": 0, "id": 1376892, "job": "Art Department Coordinator", "name": "Rebecca Jellie"}, {"credit_id": "544919ba0e0a26748f001b42", "department": "Art", "gender": 0, "id": 1376893, "job": "Set Designer", "name": "Robert Andrew Johnson"}, {"credit_id": "54491b1dc3a3680faa001b8c", "department": "Art", "gender": 0, "id": 1376895, "job": "Assistant Art Director", "name": "Mike Stassi"}, {"credit_id": "54491b79c3a3680fbb001826", "department": "Art", "gender": 0, "id": 1376897, "job": "Construction Coordinator", "name": "John Villarino"}, {"credit_id": "54491baec3a3680fb4001ce6", "department": "Art", "gender": 2, "id": 1376898, "job": "Assistant Art Director", "name": "Jeffrey Wisniewski"}, {"credit_id": "54491d2fc3a3680fb4001d07", "department": "Editing", "gender": 0, "id": 1376899, "job": "Dialogue Editor", "name": "Cheryl Nardi"}, {"credit_id": "54491d86c3a3680fa5001b2f", "department": "Editing", "gender": 0, "id": 1376901, "job": "Dialogue Editor", "name": "Marshall Winn"}, {"credit_id": "54491d9dc3a3680faa001bb0", "department": "Sound", "gender": 0, "id": 1376902, "job": "Supervising Sound Editor", "name": "Gwendolyn Yates Whittle"}, {"credit_id": "54491dc10e0a267486001bce", "department": "Sound", "gender": 0, "id": 1376903, "job": "Sound Re-Recording Mixer", "name": "William Stein"}, {"credit_id": "54491f500e0a26747c001c07", "department": "Crew", "gender": 0, "id": 1376909, "job": "Choreographer", "name": "Lula Washington"}, {"credit_id": "549599239251412c4e002a2e", "department": "Visual Effects", "gender": 0, "id": 1391692, "job": "Visual Effects Producer", "name": "Chris Del Conte"}, {"credit_id": "54959d54c3a36831b8001d9a", "department": "Visual Effects", "gender": 2, "id": 1391695, "job": "Visual Effects Supervisor", "name": "R. Christopher White"}, {"credit_id": "54959bdf9251412c4e002a66", "department": "Visual Effects", "gender": 0, "id": 1394070, "job": "Visual Effects Supervisor", "name": "Dan Lemmon"}, {"credit_id": "5495971d92514132ed002922", "department": "Sound", "gender": 0, "id": 1394129, "job": "Sound Effects Editor", "name": "Tim Nielsen"}, {"credit_id": "5592b25792514152cc0011aa", "department": "Crew", "gender": 0, "id": 1394286, "job": "CG Supervisor", "name": "Michael Mulholland"}, {"credit_id": "54959a329251416e2b004355", "department": "Crew", "gender": 0, "id": 1394750, "job": "Visual Effects Editor", "name": "Thomas Nittmann"}, {"credit_id": "54959d6dc3a3686ae9004401", "department": "Visual Effects", "gender": 0, "id": 1394755, "job": "Visual Effects Supervisor", "name": "Edson Williams"}, {"credit_id": "5495a08fc3a3686ae300441c", "department": "Editing", "gender": 0, "id": 1394953, "job": "Digital Intermediate", "name": "Christine Carr"}, {"credit_id": "55402d659251413d6d000249", "department": "Visual Effects", "gender": 0, "id": 1395269, "job": "Visual Effects Supervisor", "name": "John Bruno"}, {"credit_id": "54959e7b9251416e1e003f3e", "department": "Camera", "gender": 0, "id": 1398970, "job": "Steadicam Operator", "name": "David Emmerichs"}, {"credit_id": "54959734c3a3686ae10045e0", "department": "Sound", "gender": 0, "id": 1400906, "job": "Sound Effects Editor", "name": "Christopher Scarabosio"}, {"credit_id": "549595dd92514130fc002d79", "department": "Production", "gender": 0, "id": 1401784, "job": "Production Supervisor", "name": "Jennifer Teves"}, {"credit_id": "549596009251413af70028cc", "department": "Production", "gender": 0, "id": 1401785, "job": "Production Manager", "name": "Brigitte Yorke"}, {"credit_id": "549596e892514130fc002d99", "department": "Sound", "gender": 0, "id": 1401786, "job": "Sound Effects Editor", "name": "Ken Fischer"}, {"credit_id": "549598229251412c4e002a1c", "department": "Crew", "gender": 0, "id": 1401787, "job": "Special Effects Coordinator", "name": "Iain Hutton"}, {"credit_id": "549598349251416e2b00432b", "department": "Crew", "gender": 0, "id": 1401788, "job": "Special Effects Coordinator", "name": "Steve Ingram"}, {"credit_id": "54959905c3a3686ae3004324", "department": "Visual Effects", "gender": 0, "id": 1401789, "job": "Visual Effects Producer", "name": "Joyce Cox"}, {"credit_id": "5495994b92514132ed002951", "department": "Visual Effects", "gender": 0, "id": 1401790, "job": "Visual Effects Producer", "name": "Jenny Foster"}, {"credit_id": "549599cbc3a3686ae1004613", "department": "Crew", "gender": 0, "id": 1401791, "job": "Visual Effects Editor", "name": "Christopher Marino"}, {"credit_id": "549599f2c3a3686ae100461e", "department": "Crew", "gender": 0, "id": 1401792, "job": "Visual Effects Editor", "name": "Jim Milton"}, {"credit_id": "54959a51c3a3686af3003eb5", "department": "Visual Effects", "gender": 0, "id": 1401793, "job": "Visual Effects Producer", "name": "Cyndi Ochs"}, {"credit_id": "54959a7cc3a36811530026f4", "department": "Crew", "gender": 0, "id": 1401794, "job": "Visual Effects Editor", "name": "Lucas Putnam"}, {"credit_id": "54959b91c3a3680ff5002cb4", "department": "Visual Effects", "gender": 0, "id": 1401795, "job": "Visual Effects Supervisor", "name": "Anthony \'Max\' Ivins"}, {"credit_id": "54959bb69251412c4e002a5f", "department": "Visual Effects", "gender": 0, "id": 1401796, "job": "Visual Effects Supervisor", "name": "John Knoll"}, {"credit_id": "54959cbbc3a3686ae3004391", "department": "Visual Effects", "gender": 2, "id": 1401799, "job": "Visual Effects Supervisor", "name": "Eric Saindon"}, {"credit_id": "54959d06c3a3686ae90043f6", "department": "Visual Effects", "gender": 0, "id": 1401800, "job": "Visual Effects Supervisor", "name": "Wayne Stables"}, {"credit_id": "54959d259251416e1e003f11", "department": "Visual Effects", "gender": 0, "id": 1401801, "job": "Visual Effects Supervisor", "name": "David Stinnett"}, {"credit_id": "54959db49251413af7002975", "department": "Visual Effects", "gender": 0, "id": 1401803, "job": "Visual Effects Supervisor", "name": "Guy Williams"}, {"credit_id": "54959de4c3a3681153002750", "department": "Crew", "gender": 0, "id": 1401804, "job": "Stunt Coordinator", "name": "Stuart Thorp"}, {"credit_id": "54959ef2c3a3680fc60027f2", "department": "Lighting", "gender": 0, "id": 1401805, "job": "Best Boy Electric", "name": "Giles Coburn"}, {"credit_id": "54959f07c3a3680fc60027f9", "department": "Camera", "gender": 2, "id": 1401806, "job": "Still Photographer", "name": "Mark Fellman"}, {"credit_id": "54959f47c3a3681153002774", "department": "Lighting", "gender": 0, "id": 1401807, "job": "Lighting Technician", "name": "Scott Sprague"}, {"credit_id": "54959f8cc3a36831b8001df2", "department": "Visual Effects", "gender": 0, "id": 1401808, "job": "Animation Director", "name": "Jeremy Hollobon"}, {"credit_id": "54959fa0c3a36831b8001dfb", "department": "Visual Effects", "gender": 0, "id": 1401809, "job": "Animation Director", "name": "Orlando Meunier"}, {"credit_id": "54959fb6c3a3686af3003f54", "department": "Visual Effects", "gender": 0, "id": 1401810, "job": "Animation Director", "name": "Taisuke Tanimura"}, {"credit_id": "54959fd2c3a36831b8001e02", "department": "Costume & Make-Up", "gender": 0, "id": 1401812, "job": "Set Costumer", "name": "Lilia Mishel Acevedo"}, {"credit_id": "54959ff9c3a3686ae300440c", "department": "Costume & Make-Up", "gender": 0, "id": 1401814, "job": "Set Costumer", "name": "Alejandro M. Hernandez"}, {"credit_id": "5495a0ddc3a3686ae10046fe", "department": "Editing", "gender": 0, "id": 1401815, "job": "Digital Intermediate", "name": "Marvin Hall"}, {"credit_id": "5495a1f7c3a3686ae3004443", "department": "Production", "gender": 0, "id": 1401816, "job": "Publicist", "name": "Judy Alley"}, {"credit_id": "5592b29fc3a36869d100002f", "department": "Crew", "gender": 0, "id": 1418381, "job": "CG Supervisor", "name": "Mike Perry"}, {"credit_id": "5592b23a9251415df8001081", "department": "Crew", "gender": 0, "id": 1426854, "job": "CG Supervisor", "name": "Andrew Morley"}, {"credit_id": "55491e1192514104c40002d8", "department": "Art", "gender": 0, "id": 1438901, "job": "Conceptual Design", "name": "Seth Engstrom"}, {"credit_id": "5525d5809251417276002b06", "department": "Crew", "gender": 0, "id": 1447362, "job": "Visual Effects Art Director", "name": "Eric Oliver"}, {"credit_id": "554427ca925141586500312a", "department": "Visual Effects", "gender": 0, "id": 1447503, "job": "Modeling", "name": "Matsune Suzuki"}, {"credit_id": "551906889251415aab001c88", "department": "Art", "gender": 0, "id": 1447524, "job": "Art Department Manager", "name": "Paul Tobin"}, {"credit_id": "5592af8492514152cc0010de", "department": 

In [51]:
def extract_names(obj):
    try:
        obj = ast.literal_eval(obj)
        return [i['name'] for i in obj]
    except:
        return []

def extract_top_cast(obj):
    try:
        obj = ast.literal_eval(obj)
        return [i['name'] for i in obj[:3]]
    except:
        return []

def extract_director(obj):
    try:
        obj = ast.literal_eval(obj)
        for i in obj:
            if i['job'] == 'Director':
                return [i['name']]
        return []
    except:
        return []

In [52]:
movies["genres"] = movies["genres"].apply(extract_names)
movies["keywords"] = movies["keywords"].apply(extract_names)
movies["cast"] = movies["cast"].apply(extract_top_cast)
movies["director"] = movies["crew"].apply(extract_director)

# combine everything
movies["tags"] = movies.apply(
    lambda x: " ".join(
        x["genres"] + x["keywords"] + x["cast"] + x["director"] + [str(x["overview"])]
    ),
    axis=1
)

movies = movies[["title", "tags"]]

In [53]:
movies.head()

,title,tags
0,Avatar,Action Adventure Fantasy Science Fiction cultu...
1,Pirates of the Caribbean: At World's End,Adventure Fantasy Action ocean drug abuse exot...
2,Spectre,Action Adventure Crime spy based on novel secr...
3,The Dark Knight Rises,Action Crime Drama Thriller dc comics crime fi...
4,John Carter,Action Adventure Science Fiction based on nove...

In [54]:
movies['tags'][0]

'Action Adventure Fantasy Science Fiction culture clash future space war space colony society space travel futuristic romance space alien tribe alien planet cgi marine soldier battle love affair anti war power relations mind and soul 3d Sam Worthington Zoe Saldana Sigourney Weaver James Cameron In the 22nd century, a paraplegic Marine is dispatched to the moon Pandora on a unique mission, but becomes torn between following orders and protecting an alien civilization.'

In [55]:
movies.isnull().sum()

title    0
tags     0
dtype: int64

In [57]:
from sklearn.feature_extraction.text import TfidfVectorizer
from sklearn.metrics.pairwise import cosine_similarity

tfidf = TfidfVectorizer(stop_words="english", max_features=5000)

tfidf_matrix = tfidf.fit_transform(movies["tags"])

tfidf_sim = cosine_similarity(tfidf_matrix)

In [58]:
def recommend_tfidf(movie):
    idx = movies[movies["title"] == movie].index[0]

    scores = list(enumerate(tfidf_sim[idx]))
    scores = sorted(scores, key=lambda x: x[1], reverse=True)

    top10 = scores[1:11]

    return [movies.iloc[i[0]].title for i in top10]

**USING INSTRUCT-MODEL EMBEDDINGS**

In [59]:
!pip install -q sentence-transformers

**We have used BAAI/bge-base-en-v1.5, which is a 110M parameter transformer-based sentence embedding model built on a BERT-base encoder architecture. It is trained using contrastive learning for retrieval tasks, making it well-suited for semantic similarity and recommendation systems.**

Architecture type: BERT-base (Transformer Encoder architecture)

1. Layers: 12

2. Hidden size: 768

3. Attention heads: 12

4. Pooling: Mean pooling (to get sentence embedding)

In [60]:
from sentence_transformers import SentenceTransformer

model = SentenceTransformer("BAAI/bge-base-en-v1.5")

/usr/local/lib/python3.12/dist-packages/huggingface_hub/utils/_auth.py:93: UserWarning:
The secret `HF_TOKEN` does not exist in your Colab secrets.
To authenticate with the Hugging Face Hub, create a token in your settings tab (https://huggingface.co/settings/tokens), set it as secret in your Google Colab and restart your session.
You will be able to reuse this secret in all of your notebooks.
Please note that authentication is recommended but still optional to access public models or datasets.
  warnings.warn(

modules.json:   0%|          | 0.00/349 [00:00<?, ?B/s]

Warning: You are sending unauthenticated requests to the HF Hub. Please set a HF_TOKEN to enable higher rate limits and faster downloads.
WARNING:huggingface_hub.utils._http:Warning: You are sending unauthenticated requests to the HF Hub. Please set a HF_TOKEN to enable higher rate limits and faster downloads.

config_sentence_transformers.json:   0%|          | 0.00/124 [00:00<?, ?B/s]

README.md: 0.00B [00:00, ?B/s]

sentence_bert_config.json:   0%|          | 0.00/52.0 [00:00<?, ?B/s]

config.json:   0%|          | 0.00/777 [00:00<?, ?B/s]

model.safetensors:   0%|          | 0.00/438M [00:00<?, ?B/s]

Loading weights:   0%|          | 0/199 [00:00<?, ?it/s]

BertModel LOAD REPORT from: BAAI/bge-base-en-v1.5
Key                     | Status     |  |
------------------------+------------+--+-
embeddings.position_ids | UNEXPECTED |  |

Notes:
- UNEXPECTED	:can be ignored when loading from different task/architecture; not ok if you expect identical arch.

tokenizer_config.json:   0%|          | 0.00/366 [00:00<?, ?B/s]

vocab.txt: 0.00B [00:00, ?B/s]

tokenizer.json: 0.00B [00:00, ?B/s]

special_tokens_map.json:   0%|          | 0.00/125 [00:00<?, ?B/s]

config.json:   0%|          | 0.00/190 [00:00<?, ?B/s]

In [61]:
def build_input(text):
    return "Represent this movie for retrieval: " + text

In [62]:
embeddings = model.encode(
    [build_input(t) for t in movies["tags"]],
    normalize_embeddings=True,
    show_progress_bar=True,
    batch_size=64
)

Batches:   0%|          | 0/76 [00:00<?, ?it/s]

KeyboardInterrupt:

In [65]:
import os

save_path = f"{BASE_DIR}/tmdb-5000-embeddings-BAAI"

os.makedirs(save_path, exist_ok=True)

In [66]:
import numpy as np

np.save(f"{save_path}/embeddings.npy", embeddings)

NameError: name 'embeddings' is not defined

In [ ]:
print("Shape:", embeddings.shape)

print("\nFirst embedding (first 10 values):")
print(embeddings[0][:10])

print("\nFirst 3 embeddings (first 5 values each):")
print(embeddings[:3, :5])

In [67]:
from sklearn.metrics.pairwise import cosine_similarity
import numpy as np

def recommend_bge(movie, embeddings_path):


    embeddings = np.load(embeddings_path)


    idx = movies[movies["title"] == movie].index[0]


    scores = cosine_similarity([embeddings[idx]], embeddings)[0]


    top10 = scores.argsort()[::-1][1:11]

    return [movies.iloc[i].title for i in top10]

In [68]:
path = f"{save_path}/embeddings.npy"

recommend_bge("Avatar", path)

['Battle: Los Angeles',
 'Terminator Genisys',
 'Starship Troopers',
 'Æon Flux',
 'Prometheus',
 'Supernova',
 'The Inhabited Island',
 'Aliens',
 'Damnation Alley',
 'Battlefield Earth']

In [69]:
recommend_tfidf("Avatar")

['Aliens',
 'Alien',
 'Moonraker',
 'Alien³',
 'Silent Running',
 'Spaceballs',
 'Mission to Mars',
 'Lost in Space',
 'Planet of the Apes',
 'Lifeforce']